### ISSUE TITLE
remote URLs are not correct anymore

### ISSUE THREAD

**Issue by amtoine** [a2n-s/pkgbuilds#21]
i moved all the config-related repos to this organisation
for now, the redirection is working, but the links are still not correct anymore... :open_mouth: 

**this will have to be adressed someday in the near future** :relieved: 

@atxr
we need to find a new long-term name for this organization and apply that name to all the URLs :wink:

**Comment by amtoine** [comment]
i extend this issue to the `README` and the `VERSIONS` as well :yum: 

we need to fix the URLs, fix the description and replace the "`amtoine`"s :+1:

**Comment by dolphinau** [comment]
I can see the redirection indeed.
However I think it's not working for this command
`gh pr checkout 1`
`gh` doesn't manage to find the PR#1, it must look for it in amtoine and not goatfiles

**Comment by amtoine** [comment]
why would you want to `gh pr checkout 1` here ? :confused: 
this is not a PR :wink:

**Comment by dolphinau** [comment]
Wrong repo sorry

**Comment by amtoine** [comment]
> Wrong repo sorry
>
got it, so the issue still has to be addressed :+1:
