### ISSUE TITLE
the names of the packages are not correct anymore

### ISSUE THREAD

**Issue by amtoine** [a2n-s/pkgbuilds#23]
Since we moved from my personal dotfiles to the [goatfiles](https://github.com/goatfiles), we need to:
- rename the packages
- uninstall the old `amtoine-*-git` package locally
- reinstall the new ones
- fix the `pkgs.toml` in the [dotfiles](https://github.com/goatfiles/dotfiles)

**i think we should name the all "`goat-{PKGNAME}-git`"**

- they are all part of the [goatfiles](https://github.com/goatfiles), even things like `vim` and `paru` which are here package for the _goatfiles_
- they are all using the latest `git` revision
- that would make it easier to avoid conflict with AUR package like regular `paru` and `vim-clipboard`

**Comment by dolphinau** [comment]
So we will need to uninstall all the `amtoine-...` and install all the `goat-...` after #25?

**Comment by amtoine** [comment]
> So we will need to uninstall all the `amtoine-...` and install all the `goat-...` after #25?
>
absolutely :+1: 

none of them changed recently, so there is no urgency in doing so :ok_hand: 

however, if you want to **(1)** install a new one, **(2)** update an existing one or **(3)** reinstall your system, you'll have to make room for the new `goat-*` packages by removing the others :yum: 
the process is manual for now but should be easy :muscle:

**Comment by amtoine** [comment]
personnally, and as my `/` partition is still full, i won't update nor change the packages until a real need appears :wink:
